# Generated by Django 6.0.6 on 2026-07-07 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_referral_userprofile_loyaltymilestone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_category',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_license_plate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_make_model',
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='garage_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.garage'),
        ),
        migrations.CreateModel(
            name='VehicleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='api.vehiclecategorymaster')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='garage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garage_entries', to='api.vehiclemaster'),
        ),
        migrations.AlterUniqueTogether(
            name='garage',
            unique_together={('user', 'license_plate')},
        ),
    ]
