# Generated by Django 6.0.6 on 2026-07-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_username_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
