# Generated by Django 6.0.6 on 2026-07-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_payment_window_start_booking_requested_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.DeleteModel(
            name='AppointmentSlot',
        ),
    ]
