# Generated by Django 6.0.6 on 2026-07-09 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_booking_slot_delete_appointmentslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perk_description', models.CharField(default='Free Coffee & Console Lounge Access', max_length=255)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='api.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
