# Generated by Django 6.0.6 on 2026-07-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_digitalvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
