# Generated by Django 6.0.6 on 2026-07-23 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_assigned_date_booking_assigned_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='digitalvoucher',
            old_name='is_redeemed',
            new_name='is_cafe_discount_used',
        ),
        migrations.RemoveField(
            model_name='digitalvoucher',
            name='perk_description',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('ONLINE', 'App/Website'), ('OFFLINE', 'Walk-in/Counter')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='digitalvoucher',
            name='cafe_discount_percentage',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='digitalvoucher',
            name='free_gaming_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='digitalvoucher',
            name='is_gaming_perk_used',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MasterInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open Tab'), ('PAID', 'Settled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DETAILING', 'Workshop Detailing'), ('CAFE', 'Cafe & Lounge'), ('GAMING', 'Gaming Parlor')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='api.masterinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='GamingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('complimentary_minutes_applied', models.IntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.gamingstation')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaming_sessions', to='api.masterinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='master_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.masterinvoice'),
        ),
    ]
