# Generated by Django 6.0.6 on 2026-07-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cafeitem_gamingstation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterinvoice',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open Tab'), ('AWAITING_PAYMENT', 'Bill Finalized - Pending Payment'), ('PAID', 'Settled')], default='OPEN', max_length=20),
        ),
    ]
