name: Sync to Renation

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push Code to Renation
        env:
          SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Use the environment variable securely inside quotes
          git remote add destination "https://x-access-token:${SYNC_TOKEN}@github.com/rajamii/renation.git"
          
          git push destination main --force